version: '3.1'
services:
   mysql:
     image: mysql
     secrets:
      - source: "mysqlrootpasswd"
        target: "mysqlrootpasswd"
        mode: 0444
      - source: "mysqlpasswd"
        target: "mysqlpasswd"
        mode: 0444
     environment:
       MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysqlrootpasswd"
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: "/run/secrets/mysqlpasswd"
     volumes:
      - mysqlprod:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]
       restart_policy:
         condition: any

   wordpress:
     image: wordpress
     ports:
       - "8080:80"
     depends_on:
       - mysql
     secrets:
       - source: "mysqlpasswd"
         target: "wpdbpasswd"
         mode: 0444
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_DATABASE: wordpress
       WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wpdbpasswd"
     volumes:
      - wordpressprod:/var/www/html
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]
       restart_policy:
         condition: on-failure

volumes:
  mysqlprod:
    external: true

  wordpressprod:
    external: true

secrets:
  mysqlrootpasswd:
    external:
      name: "prodapp_mysqlrootpasswd"

secrets:
  mysqlpasswd:
    external:
      name: "prodapp_mysqlpasswd"
